site_name: Hacking The Cloud
site_description: The encyclopedia for offensive security in the cloud.
site_url: https://hackingthe.cloud/

docs_dir: content

theme:
  name: material
  logo: images/logo.png
  favicon: images/logo.png
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/github
  features:
    # - navigation.instant  Add this at a later date
    - navigation.tabs
    - navigation.indexes
    - content.action.edit
  palette:
    - scheme: slate
      primary: red
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to Dark Mode
    - scheme: default
      primary: red
      toggle:
        icon: material/toggle-switch
        name: Switch to Light Mode

markdown_extensions:
  - meta
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search
  - rss: # non-standard
      length: 200
  - awesome-pages # non-standard
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
  - redirects:
      redirect_maps:
        'aws/post_exploitation/aws_consoler.md': 'aws/general-knowledge/create_a_console_session_from_iam_credentials.md'
  - glightbox: # non-standard

extra_javascript:
  - javascripts/matomo.min.js

repo_name: Hacking The Cloud
repo_url: https://github.com/Hacking-the-Cloud/hackingthe.cloud
edit_uri: edit/main/content/

extra:
  social:
    - icon: fontawesome/brands/mastodon
      link: https://infosec.exchange/@hackingthecloud
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Frichette_n
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/nick-frichette/
    - icon: fontawesome/brands/github
      link: https://github.com/Hacking-the-Cloud
    - icon: fontawesome/solid/rss
      link: https://hackingthe.cloud/feed_rss_created.xml
